/**
 * PLACEHOLDER — regenerated by `npm run db:types`.
 *
 * Do NOT hand-edit. Once Supabase project is created and the schema migrations
 * have been applied, run:
 *
 *     npm run db:types
 *
 * to regenerate. The Pydantic models in pipeline/schemas.py mirror this shape.
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
